prescription/urls.py
from django.urls import path

from .views import (

    add_prescription,
    filtered_prescriptions,
    prescription_details,
    edit,
    delete,

)


app_name = 'prescription'


urlpatterns = [


    path('add-prescription/', add_prescription, name='add-prescription'),

    path('filtered-prescriptions/<int:id>/',
         filtered_prescriptions, name='filtered-prescriptions'),

    path('prescription-details/<int:id>/',
         prescription_details, name='prescription-details'),

    path('edit/<int:id>/', edit, name='edit'),

    path('delete/<int:id>', delete, name='delete'),


]

source/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from prescription.api.views import PrescriptionList
from prescription.views import (

    add_prescription,
    filtered_prescriptions,
    prescription_details,
    edit,
    delete,

)


from .views import home


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', home, name='home'),


    path('edit/<int:id>/', edit, name='edit'),

    path('delete/<int:id>', delete, name='delete'),

    path('prescription-details/<int:id>/',
         prescription_details, name='prescription-details'),


    # API
    path('api/v1/prescription/', PrescriptionList.as_view()),

    path('', include('prescription.urls', namespace='prescription')),

    path('', include('custom_users.urls', namespace='custom_users')),





] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prescription/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Prescription(models.Model):

    GENDER_STATUS = (
        ('Male', 'MALE'),
        ('Female', 'FEMALE'),
        ('Other', 'OTHER'),
    )

    prescription_date = models.DateField(default=timezone.now, blank=False)
    patient_name = models.CharField(max_length=50, blank=False)
    patient_age = models.PositiveIntegerField(blank=False)
    patient_gender = models.CharField(max_length=10, choices=GENDER_STATUS, blank=False, default='OTHER')
    diagnosis = models.CharField(max_length=100000)
    medicines = models.CharField(max_length=100000)
    next_visit_date = models.DateTimeField(auto_now_add=False, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.patient_name

prescription/forms.py
from django import forms
from django.forms import TextInput, Select, SelectDateWidget, TimeInput, NumberInput

from .models import Prescription


class PrescriptionAddForm(forms.ModelForm):
    class Meta:
        model = Prescription
        fields = ['patient_name', 'patient_age', 'patient_gender', 'diagnosis', 'medicines',
                  'prescription_date', 'next_visit_date', 'user']

        widgets = {
            'patient_name': TextInput(attrs={'class': 'form-control'}),
            'patient_age': NumberInput(attrs={'class': 'form-control'}),
            'patient_gender': Select(attrs={'class': 'form-control'}),
            'diagnosis': TextInput(attrs={'class': 'form-control'}),
            'medicines': TextInput(attrs={'class': 'form-control'}),
            'prescription_date': SelectDateWidget(attrs={'class': 'form-control'}),
            'next_visit_date': SelectDateWidget(attrs={'class': 'form-control'}),
        }

prescription/api/views.py
from django.shortcuts import render
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response

from prescription.models import Prescription
from .serializers import PrescriptionSerializer


class PrescriptionList(APIView):

    def get(self, request, id=None):

        prescription_list = Prescription.objects.all().order_by('-id')

        prescription_serialization = PrescriptionSerializer(prescription_list, many=True)

        return Response(prescription_serialization.data)

    

prescription/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User

from .forms import PrescriptionAddForm
from .models import Prescription

from source.views import home


#################################################################################################


@login_required
def add_prescription(request):

    if request.method == 'POST':
        form = PrescriptionAddForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, 'Prescription Added Successfully!')

            return redirect('prescription:filtered-prescriptions', id=request.user.id)

    else:
        form = PrescriptionAddForm()

    template = 'prescription/add_prescription.html'
    context = {'form': form}

    return render(request, template, context)

#################################################################################################


@login_required
def filtered_prescriptions(request, id=None):

    current_user = User.objects.get(id=id)
    filtered_prescriptions_by_user = Prescription.objects.filter(
        user=current_user)

    template = 'prescription/filtered_prescriptions.html'

    context = {'filtered_prescriptions_by_user': filtered_prescriptions_by_user}

    return render(request, template, context)

#################################################################################################


@login_required
def prescription_details(request, id=None):

    single_prescriptions_details = Prescription.objects.get(id=id)

    template = 'prescription/single_prescriptions_details.html'

    context = {'single_prescriptions_details': single_prescriptions_details}

    return render(request, template, context)

#################################################################################################


@login_required
def edit(request, id=None):

    query = Prescription.objects.get(id=id)
    form = PrescriptionAddForm(request.POST or None, instance=query)

    if request.method == 'POST':
        if form.is_valid():
            form.save()

            return redirect('prescription-details', id)
            # return redirect('prescription:prescription-details', id=request.user.id)

    context = {'form': form}
    template = 'prescription/edit.html'

    return render(request, template, context)

#################################################################################################


@login_required
def delete(request, id=None):

    delete_query = get_object_or_404(Prescription, id=id)

    if request.method == 'POST':

        delete_query.delete()
        return redirect('prescription:filtered-prescriptions', id=request.user.id)

    template = 'prescription/delete.html'
    context = {'delete_query': delete_query}
    return render(request, template, context)

#################################################################################################

templates/prescription/add_prescription.html
{% extends 'base.html' %}

{% block title %}Add Prescription{% endblock %}

{% block content %}
    <hr>
    <h1>Add Prescription</h1>
    <hr>

    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <hr>
        <button type="submit" class="btn btn-success">ADD</button>
        <hr>
        <br>
    </form>

{% endblock %}

templates/prescription/delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock %}

{% block content %}
    <hr>
    <h1>Delete</h1>
    <hr>

    <form method="post">
        {% csrf_token %}

        Are you sure want to DELETE <strong style="color: blue">{{delete_query}}</strong>?

        <hr>
        <button type="submit" class="btn btn-danger">Delete</button>
        <hr>
    </form>

{% endblock content %}

templates/prescription/edit.html
{% extends 'base.html' %}

{% block title %}Edit{% endblock %}

{% block content %}
    <hr>
    <h1>Edit</h1>
    <hr>

    <form method="post">
        {% csrf_token %}

        {{form.as_p}}
        <hr>
        <button type="submit" class="btn btn-success">SAVE</button>
        <hr>
    </form>

{% endblock content %}

templates/prescription/filtered_prescriptions.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <hr>

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    <hr>
    <h1><strong style="color: orangered">{{ request.user }}'s</strong> Dashboard</h1>
    <hr>

    <h2 style="color: purple">Your Tasks:</h2>
    <hr>

    <a href="{% url 'prescription:add-prescription' %}">
        <button type="button" class="btn btn-success">Add Prescription</button>
    </a>
    <br>
    <br>

    <table class="table table-striped table-bordered table-hover mb-4">
        <thead>
        <tr class="bg-info text-white">
            <th colspan="2">Newly Added Prescriptions:</th>
        </tr>
        <tr>
            <th>SL NO.</th>
            <th> Patient Name </th>
        </tr>
        </thead>

        <tbody>

        {% for filter_data in filtered_prescriptions_by_user %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <th><a href="{% url 'prescription:prescription-details' filter_data.id %}">{{ filter_data.patient_name }}</a></th>
            </tr>
        {% endfor %}

        

        </tbody>
    </table>


{% endblock content %}

templates/prescription/single_prescriptions_details.html
{% extends 'base.html' %}

{% block title %}Single Prescription{% endblock %}

{% block content %}
    <hr>

    <h1 style="color: purple">Single Prescription Details</h1>
    <hr>

    <h4>ID: <strong style="color: red">{{ single_prescriptions_details.id }}</strong></h4>
    <br>
    <h3>Patient Name: <strong style="color: blue">{{ single_prescriptions_details.patient_name }}</strong></h3>
    <h3>Patient Age: <strong style="color: blue">{{ single_prescriptions_details.patient_age }}</strong></h3>
    <h3>Patient Gender: <strong style="color: blue">{{ single_prescriptions_details.patient_gender }}</strong></h3>
    <h3>Diagnosis: <strong style="color: blue">{{ single_prescriptions_details.diagnosis }}</strong></h3>
    <h3>Medicines: <strong style="color: blue">{{ single_prescriptions_details.medicines }}</strong></h3>
    <h3>Prescription Date: <strong style="color: blue">{{ single_prescriptions_details.prescription_date }}</strong></h3>
    <h3>Next Visit Date: <strong style="color: blue">{{ single_prescriptions_details.next_visit_date }}</strong></h3>
    <br>
    <h3>Managed By: <strong style="color: red">{{ single_prescriptions_details.user.username }}</strong></h3>
    <hr>

    <a href="{% url 'prescription:filtered-prescriptions' id=request.user.id %}">
        <button type="button" class="btn btn-success">Back To Dashboard</button>
    </a>

    <a href="{% url 'prescription:edit' single_prescriptions_details.id %}">
        <button type="button" class="btn btn-danger">Edit</button>
    </a>

    <a href="{% url 'prescription:delete' single_prescriptions_details.id %}">
        <button type="button" class="btn btn-danger">Delete</button>
    </a>

    <br>
    <hr>

{% endblock %}