custom_users/urls.py
from django.urls import path

from .views import (

    sign_up,

    login_request,

    logout_request,
)


app_name = 'custom_users'


urlpatterns = [

    path('signup/', sign_up, name='signup'),

    path('login/', login_request, name='login'),

    path('logout/', logout_request, name='logout'),

]

prescription/urls.py
from django.urls import path

from .views import (

    add_prescription,
    filtered_prescriptions,
    prescription_details,
    edit,
    delete,

)


app_name = 'prescription'


urlpatterns = [


    path('add-prescription/', add_prescription, name='add-prescription'),

    path('filtered-prescriptions/<int:id>/',
         filtered_prescriptions, name='filtered-prescriptions'),

    path('prescription-details/<int:id>/',
         prescription_details, name='prescription-details'),

    path('edit/<int:id>/', edit, name='edit'),

    path('delete/<int:id>', delete, name='delete'),


]

source/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from prescription.api.views import PrescriptionList
from prescription.views import (

    add_prescription,
    filtered_prescriptions,
    prescription_details,
    edit,
    delete,

)


from .views import home


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', home, name='home'),


    path('edit/<int:id>/', edit, name='edit'),

    path('delete/<int:id>', delete, name='delete'),

    path('prescription-details/<int:id>/',
         prescription_details, name='prescription-details'),


    # API
    path('api/v1/prescription/', PrescriptionList.as_view()),

    path('', include('prescription.urls', namespace='prescription')),

    path('', include('custom_users.urls', namespace='custom_users')),





] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
          crossorigin="anonymous" />
</head>

<body>

<div class="container">
    <hr>

    <a href="{% url 'home' %}">
        <button type="button" class="btn btn-dark">Home</button>
    </a>

    {% if user.is_authenticated %}

        <a href="{% url 'custom_users:logout' %}">
            <button type="button" class="btn btn-danger">Logout</button>
        </a>

    {% else %}

        <a href="{% url 'custom_users:login' %}">
            <button type="button" class="btn btn-success">Login</button>
        </a>

        <a href="{% url 'custom_users:signup' %}">
            <button type="button" class="btn btn-primary">SignUp</button>
        </a>

    {% endif %}

    {% block content %}


    {% endblock %}

</div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <hr>
    <h1>Home Page</h1>
    <hr>

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    {% if request.user.is_authenticated %}
        <h3>Welcome @<strong style="color: orangered">{{ user.username }}</strong>!</h3>
        <hr>
        <br>

        <a href="{% url 'prescription:filtered-prescriptions' id=request.user.id %}">
            <button type="button" class="btn btn-success">Go To Your Dashboard</button>
        </a>

    {% else %}
        <h1 style="color: red">You are not logged in!</h1>
    {% endif %}

{% endblock content %}